name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Verify Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify Dockerfile
        run: docker compose config
      - name: Verify Dockerfile
        run: docker compose build
